### ISSUE TITLE
Unable to find an appropriate codec for video/mjpeg

### ISSUE THREAD

**Issue by JSiLi** [archersmind/EncoderDecoderTestForMJPEG#1]
Hi 

I build your project and got "Unable to find an appropriate codec for video/mjpeg" log

seem new mediacodec version are not support mjpeg.

Do you have any idea to solve it?

**Comment by archersmind** [comment]
@JSiLi  maybe the mime-type is vary between different versions.  You might want to try video/x-mjpeg, it's better to trace down the codes of MediaCodes API and see what's going wrong. It's being a long time since I move to another platform, so sorry I can't help you.
