### ISSUE TITLE
Unable to find an appropriate codec for video/mjpeg 

### ISSUE THREAD

**Issue by fmer** [archersmind/EncoderDecoderTestForMJPEG#2]
hi, How about "Unable to find an appropriate codec for video/mjpeg "?

**Comment by archersmind** [comment]
means you don't have a mjpeg decoder on your platform. Check the media_codecs.xml see if you can find one.

**Comment by fmer** [comment]
hello, 
      Thank you for your reply
      I tested that most Android phones do not have this dencoder, Is your phone customizable? Do you have WeChat or QQ?May I ask you some questions?




------------------ 原始邮件 ------------------
发件人: "Alan";<notifications@github.com>;
发送时间: 2017年12月8日(星期五) 下午2:15
收件人: "archersmind/EncoderDecoderTestForMJPEG"<EncoderDecoderTestForMJPEG@noreply.github.com>;
抄送: "Android-林澎"<fmer_lin@foxmail.com>; "Author"<author@noreply.github.com>; 
主题: Re: [archersmind/EncoderDecoderTestForMJPEG] Unable to find anappropriate codec for video/mjpeg (#2)




means you don't have a mjpeg decoder on your platform. Check the media_codecs.xml see if you can find one.

**Comment by archersmind** [comment]
Then you should have port this codec first.
